analyzer:
  errors:
    unused_import: ignore
include: package:flutter_lints/flutter.yaml

linter:
  rules:
    avoid_print: false
    prefer_const_constructors: true
    prefer_const_literals_to_create_immutables: true
    unnecessary_this: false
    prefer_single_quotes: true
    always_use_package_imports: true
